[versions]
unstyled = "1.46.1"
lucide = "1.0.0"
ripple = "1.0.0"

# compose
compose = "1.9.1"
composeHotReload = "1.0.0-rc02"

#kotlin
kotlin = "2.2.20"

# android specific
agp = "8.11.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"

[libraries]
composables-composeunstyled = { module = "com.composables:core", version.ref = "unstyled" }
composables-ripple = { module = "com.composables:ripple-indication", version.ref = "ripple" }
composables-icons-lucide = { module = "com.composables:icons-lucide", version.ref = "lucide" }
androidx-activitycompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-compose-hotreload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }